=== yoni-wolf/private-tranaction-families/transaction_generator/config/config_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "/config_schema.json",
  "title": "Config Schema",
  "description": "Sawtooth transaction processor generator configuration schema",
  "type": "object",
  "properties": {
    "family_name": {
      "description": "family name for the transaction processor",
      "type": "string"
    },
    "family_version": {
      "description": "version of the transaction processor, must be grater than 0",
      "type": "number",
      "minimum": 0,
      "exclusiveMinimum": true
    },
    "payload_encoding": {
      "description": "how transaction payload will be encoded, only cbor or json are valid",
      "type": "string",
      "enum": [
        "cbor",
        "json"
      ]
    },
    "signer_priv_key": {
      "description": "path to file containing the signer private key in hex format, if missing a random key will be generated",
      "type": "string"
    },
    "txn_payload": {
      "description": "array of transactions payload in json format, must have at least one, each item should match payload_schema",
      "type": "array",
      "minItems": 1,
      "items": {
        "oneOf": [
          {
            "$ref": "#definitions/payload"
          },
          {
            "$ref": "#definitions/acl_payload"
          }
        ]
      },
      "uniqueItems": false
    }
  },
  "required": [
    "family_name",
    "family_version",
    "payload_encoding",
    "txn_payload"
  ],
  "definitions": {
    "payload": {
      "type": "object",
      "properties": {
        "Verb": {
          "description": "action to be taken, only accept 'set', 'inc' or 'dec'",
          "type": "string",
          "enum": [
            "set",
            "inc",
            "dec"
          ]
        },
        "Value": {
          "description": "value for the key, must be grater than 0",
          "type": "number",
          "minimum": 0,
          "exclusiveMinimum": true
        },
        "Name": {
          "description": "key name",
          "type": "string"
        }
      },
      "required": [
        "Verb",
        "Name",
        "Value"
      ]
    },
    "acl_payload": {
      "type": "object",
      "properties": {
        "Type": {
          "description": "used to detect this type of transaction, must be private_ledger_administration",
          "type": "string",
          "enum": [
            "private_ledger_administration"
          ]
        },
        "Action": {
          "description": "action to be taken",
          "type": "string",
          "enum": [
            "add_member",
            "add_group",
            "remove_member",
            "remove_group",
            "add_access",
            "remove_access",
            "add_to_group",
            "remove_from_group",
            "change_member_key",
            "update_svn"
          ]
        },
        "Key": {
          "description": "public key for member, group id for group",
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string"
          },
          "uniqueItems": true
        },
        "Address": {
          "description": "(optional) array of address prefix (not including first 6 characters of family name) to assign to members or groups, prefix of 62 zeroes is allready reserved",
          "type": "array",
          "minItems": 0,
          "items": {
            "type": "string"
          },
          "uniqueItems": true
        },
        "Group": {
          "description": "(optional) group that this member should belong to, group name must be added first with add_group txn",
          "type": "string"
        },
        "new_svn": {
          "description": "(optional) new svn for update svn transaction",
          "type": "integer"
        }
      },
      "required": [
        "Type",
        "Action",
        "Key"
      ]
    }
  }
}

=== yoni-wolf/private-tranaction-families/Debug/txn_gen_svn.json
{
  "family_name": "private_intkey",
  "family_version": 1.0,
  "payload_encoding": "json",
  "signer_priv_key": "admin_keys/client_private_key.hexstr",
  "txn_payload": [
    {
      "Type": "private_ledger_administration",
      "Action": "update_svn",
      "Key": [
        "0231eacee6877831deea3f2b7bf224ca2231fc2b86be04d72a15d5e88be46fd0a9"
      ],
      "new_svn": 0
    }
  ]
}

=== yoni-wolf/private-tranaction-families/Debug/txn_gen_acl.json
{
  "family_name": "private_intkey",
  "family_version": 1.0,
  "payload_encoding": "json",
  "signer_priv_key": "client1_keys/client_private_key.hexstr",
  "txn_payload": [
    {
      "Type": "private_ledger_administration",
      "Action": "add_member",
      "Key": [
	"0375921E1176D3BA51B09482C4F322A7AAAD89A3910C4B0F3B640380AEC84A8FCB"
      ],
      "Address": [
        "bb563a905f1957a0dd5fbf218d5d402d303ece"
     ]
    }
  ]
}

=== yoni-wolf/private-tranaction-families/Debug/txn_gen_example.json
{
  "family_name": "private_intkey",
  "family_version": 1.0,
  "payload_encoding": "json",
  "signer_priv_key": "client1_keys/client_private_key.hexstr",
  "txn_payload":[
    {"Verb": "set", "Name": "Test", "Value": 54321, "Size": 100, "Prefix": "bb563a905f1957a0dd5fbf218d5d402d303ece"},
    {"Verb": "inc", "Name": "Test", "Value": 2, "Prefix": "bb563a905f1957a0dd5fbf218d5d402d303ece"}
  ]
}
